services:
  postgres:
    image: postgres:latest
    env_file:
      - ./.env
    container_name: postgres_db_messages
    ports:
      - '5432:5432'
    volumes:
      - rust_messages_data:/var/lib/postgresql/data


  pgadmin_web:
    image: dpage/pgadmin4
    container_name: pgadmin_web
    env_file:
      - ./.env
    ports:
      - '1488:80'

  rust_app:
    build:
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - network
    env_file:
      - ./.env

volumes:
  rust_messages_data:

networks:
  network: