version: '3.8'
services:
  postgres:
    image: postgres:latest
    env_file:
      - ./.env
    container_name: postgres_db_messages
    ports:
      - '5432:5432'
    volumes:
      - rust_messages_data:/var/lib/postgresql/data

volumes:
  rust_messages_data: